/**
 * ============================================================
 *  FUNA DIGITAL — translations.js
 *  Archivo central de traducciones: EN / ES / AR
 * ------------------------------------------------------------
 *  Para agregar texto nuevo al sitio:
 *  1. Añade la clave en los 3 idiomas abajo
 *  2. Pon data-i18n="tu-clave" en el elemento HTML
 *  ¡Listo! No toques nada más.
 * ============================================================
 */

window.FUNA_LANG = {

  en: {
    "nav.home":"Home","nav.about":"About Us","nav.results":"Results","nav.blog":"Blog","nav.pulse":"Pulse","nav.contact":"Contact","nav.cta":"Get Started",
    "hero.tag":"Dubai's Growth Marketing Agency","hero.line1":"WE MAKE","hero.line2":"BRANDS UN-","hero.line3":"STOPPABLE.","hero.sub":"Lead Generation · Paid Media · Content · AI · Branding","hero.desc":"We don't just run campaigns. We build marketing systems that generate leads, convert customers, and scale revenue — fast.","hero.cta1":"Start Growing","hero.cta2":"Our Services","hero.stat1.num":"8+","hero.stat1.lbl":"Years Experience","hero.stat2.num":"168+","hero.stat2.lbl":"Campaigns","hero.stat3.num":"50+","hero.stat3.lbl":"Brands Scaled",
    "marquee.items":"Lead Generation ✦ Paid Media ✦ Content Creation ✦ AI Marketing ✦ Branding ✦ Ecommerce ✦ Automation ✦ Growth Marketing",
    "services.tag":"What We Do","services.title":"END-TO-END SOLUTIONS TO GROW YOUR BUSINESS","services.desc":"From strategy to execution, we build marketing systems that drive real results. Starting from AED 3,000/month.",
    "s1.title":"Lead Generation","s1.desc":"High-intent leads delivered to your pipeline through targeted funnels, landing pages, and conversion-optimized campaigns.",
    "s2.title":"Paid Media","s2.desc":"Meta Ads, Google Ads, TikTok Ads, LinkedIn — we manage your budget like it's ours and obsess over ROAS.",
    "s3.title":"Content Creation","s3.desc":"Reels, carousels, UGC, video production — content that stops the scroll and builds brand loyalty at scale.",
    "s4.title":"AI Marketing","s4.desc":"AI-powered ad copy, automated workflows, chatbots and predictive targeting — the future of marketing, today.",
    "s5.title":"Branding","s5.desc":"Identity systems, positioning, visual language — we build brands that people remember and competitors fear.",
    "s6.title":"Ecommerce & Automation","s6.desc":"Shopify builds, email flows, CRM automation, retargeting — full-stack ecommerce growth systems that run 24/7.",
    "s7.title":"Marketing Audit & Consulting","s7.desc":"Full brand audit — channels, competitors, funnel, budget — delivered as a concrete action plan to scale your business.",
    "s8.title":"Social Media Management","s8.desc":"Full social media management — strategy, content calendar, design, copywriting and engagement. Your community grows while we run it.",
    "s9.title":"Web & App Development","s9.desc":"Websites, landing pages and apps that convert. Premium design, real speed and SEO optimization.",
    "about.tag":"Who We Are","about.title":"GROWTH OBSESSED.","about.p1":"Funa is a growth marketing agency based in Dubai, built for brands that are serious about scaling. We combine data, creativity, and automation to build marketing systems that work while you sleep.","about.p2":"We don't believe in vanity metrics. We believe in revenue, leads, and measurable ROI — delivered fast, with full transparency.","about.li1":"Growth Marketing Strategy","about.li2":"Paid Media Management","about.li3":"Content & Creative Production","about.li4":"AI-Powered Automation","about.li5":"Full-Funnel Analytics","about.cta":"Work With Us",
    "results.tag":"Track Record","results.title":"REAL RESULTS.","results.stat1.num":"10X","results.stat1.lbl":"Average ROAS","results.stat1.sub":"Average return on ad spend across all paid media campaigns in 2024.","results.stat2.num":"50+","results.stat2.lbl":"Brands Scaled","results.stat2.sub":"From Dubai startups to regional enterprises across 8+ industries.","results.stat3.num":"2M+","results.stat3.lbl":"Leads Generated","results.stat3.sub":"Qualified leads delivered to our clients through performance campaigns.","results.stat4.num":"98%","results.stat4.lbl":"Client Retention","results.stat4.sub":"Because results speak louder than promises. Our clients stay.",
    "process.tag":"How We Work","process.title":"OUR PROCESS","process.s1.title":"Discovery","process.s1.desc":"Deep-dive audit of your brand, market, competitors, and current performance.","process.s2.title":"Strategy","process.s2.desc":"Custom growth plan with channel mix, budget allocation, and KPI targets.","process.s3.title":"Create","process.s3.desc":"High-converting creatives, copy, landing pages, and campaign assets built.","process.s4.title":"Launch","process.s4.desc":"Campaigns go live across all channels with real-time monitoring and optimization.","process.s5.title":"Scale","process.s5.desc":"Double down on what works, automate the machine, and compound growth.",
    "testimonials.tag":"Client Love","testimonials.title":"WHAT THEY SAY","t1.text":"Funa completely transformed our digital presence. Within 3 months, our lead volume tripled and our cost per lead dropped by 60%. They don't just run ads — they build systems.","t1.name":"Ahmed K.","t1.role":"CEO · Real Estate Developer, Dubai","t2.text":"Best marketing decision we made. Our ecommerce revenue went from AED 80K to AED 400K/month in 6 months. The team is obsessed with results and it shows.","t2.name":"Sara L.","t2.role":"Founder · Fashion Brand, UAE","t3.text":"Funa's content team is genuinely exceptional. Our Instagram went from 2K to 18K followers in 4 months, and more importantly, it's actually converting to bookings.","t3.name":"Marco R.","t3.role":"Director · F&B Group, Dubai",
    "cta.tag":"Ready To Scale?","cta.title":"LET'S BUILD SOMETHING BIG.","cta.desc":"Answer 5 quick questions. We'll get back to you within 24 hours.",
    "form.step1.title":"What's your name & company?","form.step2.title":"How can we reach you?","form.step3.title":"What service do you need?","form.step4.title":"What's your monthly budget?","form.step5.title":"Almost done. Confirm your details.","form.btn.next":"Continue →","form.btn.back":"← Back","form.btn.send":"Send Message →","form.success":"We'll reach out within 24 hours. Talk soon.","form.reply":"We respond within 24 hours",
    "industries.tag":"Industries We Serve",
    "pulse.tag":"Free Monthly Report","pulse.title":"DUBAI MARKETING PULSE","pulse.desc":"The monthly report for businesses and marketers in the UAE. Real data, real trends, zero fluff.","pulse.li1":"UAE market trends & platform updates","pulse.li2":"What's working in Dubai right now","pulse.li3":"Industry benchmarks & ad costs","pulse.li4":"One actionable tip per issue","pulse.cta":"Get the Report","pulse.sub":"Free. Every month. No spam, ever.",
    "footer.desc":"Growth Marketing Agency · Dubai, UAE","footer.services":"Services","footer.company":"Company","footer.industries":"Industries","footer.copy":"© 2026 Funa Digital Marketing. All rights reserved. Dubai, UAE.","footer.privacy":"Privacy Policy","footer.terms":"Terms & Conditions"
  },

  es: {
    "nav.home":"Inicio","nav.about":"Nosotros","nav.results":"Resultados","nav.blog":"Blog","nav.pulse":"Pulse","nav.contact":"Contacto","nav.cta":"Empezar",
    "hero.tag":"Agencia de Marketing de Crecimiento en Dubái","hero.line1":"HACEMOS","hero.line2":"MARCAS IN-","hero.line3":"DETENIBLES.","hero.sub":"Generación de Leads · Medios Pagados · Contenido · IA · Branding","hero.desc":"No solo ejecutamos campañas. Construimos sistemas de marketing que generan leads, convierten clientes y escalan ingresos — rápido.","hero.cta1":"Empezar a Crecer","hero.cta2":"Nuestros Servicios","hero.stat1.num":"8+","hero.stat1.lbl":"Años de Experiencia","hero.stat2.num":"168+","hero.stat2.lbl":"Campañas","hero.stat3.num":"50+","hero.stat3.lbl":"Marcas Escaladas",
    "marquee.items":"Generación de Leads ✦ Medios Pagados ✦ Creación de Contenido ✦ Marketing con IA ✦ Branding ✦ Ecommerce ✦ Automatización ✦ Marketing de Crecimiento",
    "services.tag":"Lo Que Hacemos","services.title":"SOLUCIONES INTEGRALES PARA HACER CRECER TU NEGOCIO","services.desc":"De la estrategia a la ejecución, construimos sistemas de marketing que generan resultados reales. Desde AED 3,000/mes.",
    "s1.title":"Generación de Leads","s1.desc":"Leads de alta intención entregados a tu pipeline a través de funnels dirigidos, landing pages y campañas optimizadas para conversión.",
    "s2.title":"Medios Pagados","s2.desc":"Meta Ads, Google Ads, TikTok Ads, LinkedIn — gestionamos tu presupuesto como si fuera nuestro y estamos obsesionados con el ROAS.",
    "s3.title":"Creación de Contenido","s3.desc":"Reels, carruseles, UGC, producción de video — contenido que detiene el scroll y construye lealtad de marca a escala.",
    "s4.title":"Marketing con IA","s4.desc":"Copy publicitario impulsado por IA, flujos de trabajo automatizados, chatbots y segmentación predictiva — el futuro del marketing, hoy.",
    "s5.title":"Branding","s5.desc":"Sistemas de identidad, posicionamiento, lenguaje visual — construimos marcas que la gente recuerda y los competidores temen.",
    "s6.title":"Ecommerce y Automatización","s6.desc":"Tiendas Shopify, flujos de email, automatización CRM, retargeting — sistemas completos de crecimiento ecommerce que funcionan 24/7.",
    "s7.title":"Auditoría y Consultoría de Marketing","s7.desc":"Auditoría completa de marca — canales, competidores, embudo, presupuesto — entregada como un plan de acción concreto.",
    "s8.title":"Gestión de Redes Sociales","s8.desc":"Gestión completa de redes sociales — estrategia, calendario de contenido, diseño, redacción y engagement. Tu comunidad crece mientras nosotros la gestionamos.",
    "s9.title":"Desarrollo Web y de Apps","s9.desc":"Sitios web, landing pages y apps que convierten. Diseño premium, velocidad real y optimización SEO.",
    "about.tag":"Quiénes Somos","about.title":"OBSESIONADOS CON EL CRECIMIENTO.","about.p1":"Funa es una agencia de marketing de crecimiento con sede en Dubái, construida para marcas serias en escalar. Combinamos datos, creatividad y automatización para construir sistemas de marketing que trabajan mientras duermes.","about.p2":"No creemos en métricas de vanidad. Creemos en ingresos, leads y ROI medible — entregado rápido, con total transparencia.","about.li1":"Estrategia de Marketing de Crecimiento","about.li2":"Gestión de Medios Pagados","about.li3":"Producción de Contenido y Creatividad","about.li4":"Automatización con Inteligencia Artificial","about.li5":"Analítica de Embudo Completo","about.cta":"Trabajar Con Nosotros",
    "results.tag":"Historial","results.title":"RESULTADOS REALES.","results.stat1.num":"10X","results.stat1.lbl":"ROAS Promedio","results.stat1.sub":"Retorno promedio sobre gasto publicitario en todas las campañas de medios pagados en 2024.","results.stat2.num":"50+","results.stat2.lbl":"Marcas Escaladas","results.stat2.sub":"Desde startups de Dubái hasta empresas regionales en más de 8 industrias.","results.stat3.num":"2M+","results.stat3.lbl":"Leads Generados","results.stat3.sub":"Leads calificados entregados a nuestros clientes a través de campañas de rendimiento.","results.stat4.num":"98%","results.stat4.lbl":"Retención de Clientes","results.stat4.sub":"Porque los resultados hablan más fuerte que las promesas. Nuestros clientes se quedan.",
    "process.tag":"Cómo Trabajamos","process.title":"NUESTRO PROCESO","process.s1.title":"Descubrimiento","process.s1.desc":"Auditoría profunda de tu marca, mercado, competidores y rendimiento actual.","process.s2.title":"Estrategia","process.s2.desc":"Plan de crecimiento personalizado con mix de canales, asignación de presupuesto y objetivos KPI.","process.s3.title":"Crear","process.s3.desc":"Creatividades de alta conversión, copy, landing pages y activos de campaña construidos.","process.s4.title":"Lanzar","process.s4.desc":"Las campañas se activan en todos los canales con monitoreo en tiempo real y optimización.","process.s5.title":"Escalar","process.s5.desc":"Doblar apuesta en lo que funciona, automatizar la máquina y componer crecimiento.",
    "testimonials.tag":"Lo Que Dicen","testimonials.title":"TESTIMONIOS","t1.text":"Funa transformó completamente nuestra presencia digital. En 3 meses, nuestro volumen de leads se triplicó y el costo por lead bajó un 60%. No solo hacen anuncios — construyen sistemas.","t1.name":"Ahmed K.","t1.role":"CEO · Desarrolladora Inmobiliaria, Dubái","t2.text":"La mejor decisión de marketing que tomamos. Nuestros ingresos de ecommerce pasaron de AED 80K a AED 400K/mes en 6 meses. El equipo está obsesionado con los resultados y se nota.","t2.name":"Sara L.","t2.role":"Fundadora · Marca de Moda, EAU","t3.text":"El equipo de contenido de Funa es genuinamente excepcional. Nuestro Instagram pasó de 2K a 18K seguidores en 4 meses, y lo más importante, realmente está convirtiendo en reservas.","t3.name":"Marco R.","t3.role":"Director · Grupo de F&B, Dubái",
    "cta.tag":"¿Listo Para Escalar?","cta.title":"CONSTRUYAMOS ALGO GRANDE.","cta.desc":"Responde 5 preguntas rápidas. Te contactamos en menos de 24 horas.",
    "form.step1.title":"¿Cuál es tu nombre y empresa?","form.step2.title":"¿Cómo podemos contactarte?","form.step3.title":"¿Qué servicio necesitas?","form.step4.title":"¿Cuál es tu presupuesto mensual?","form.step5.title":"Casi listo. Confirma tus datos.","form.btn.next":"Continuar →","form.btn.back":"← Atrás","form.btn.send":"Enviar Mensaje →","form.success":"Te contactamos en menos de 24 horas. ¡Hasta pronto!","form.reply":"Respondemos en menos de 24 horas",
    "industries.tag":"Industrias que Servimos",
    "pulse.tag":"Reporte Mensual Gratuito","pulse.title":"DUBAI MARKETING PULSE","pulse.desc":"El reporte mensual para empresas y marketers en los EAU. Datos reales, tendencias reales, sin relleno.","pulse.li1":"Tendencias del mercado UAE y actualizaciones de plataformas","pulse.li2":"Qué está funcionando en Dubái ahora mismo","pulse.li3":"Benchmarks de la industria y costos de anuncios","pulse.li4":"Un consejo accionable por edición","pulse.cta":"Obtener el Reporte","pulse.sub":"Gratis. Cada mes. Sin spam, jamás.",
    "footer.desc":"Agencia de Marketing de Crecimiento · Dubái, EAU","footer.services":"Servicios","footer.company":"Empresa","footer.industries":"Industrias","footer.copy":"© 2026 Funa Digital Marketing. Todos los derechos reservados. Dubái, EAU.","footer.privacy":"Política de Privacidad","footer.terms":"Términos y Condiciones"
  },

  ar: {
    "nav.home":"الرئيسية","nav.about":"من نحن","nav.results":"النتائج","nav.blog":"المدونة","nav.pulse":"بولس","nav.contact":"تواصل معنا","nav.cta":"ابدأ الآن",
    "hero.tag":"وكالة التسويق للنمو في دبي","hero.line1":"نصنع","hero.line2":"علامات تجارية","hero.line3":"لا تُوقَف.","hero.sub":"توليد عملاء محتملين · إعلانات مدفوعة · محتوى · ذكاء اصطناعي · علامة تجارية","hero.desc":"لا نكتفي بإدارة الحملات. نبني أنظمة تسويقية تولّد عملاء محتملين وتحوّل العملاء وتُضاعف الإيرادات — بسرعة.","hero.cta1":"ابدأ النمو","hero.cta2":"خدماتنا","hero.stat1.num":"+8","hero.stat1.lbl":"سنوات من الخبرة","hero.stat2.num":"+168","hero.stat2.lbl":"حملة إعلانية","hero.stat3.num":"+50","hero.stat3.lbl":"علامة تجارية مُطوَّرة",
    "marquee.items":"توليد عملاء محتملين ✦ إعلانات مدفوعة ✦ إنشاء محتوى ✦ تسويق بالذكاء الاصطناعي ✦ علامة تجارية ✦ تجارة إلكترونية ✦ أتمتة ✦ تسويق النمو",
    "services.tag":"ما نقدمه","services.title":"حلول متكاملة لتنمية أعمالك","services.desc":"من الاستراتيجية إلى التنفيذ، نبني أنظمة تسويقية تحقق نتائج حقيقية. ابتداءً من 3,000 درهم/شهر.",
    "s1.title":"توليد العملاء المحتملين","s1.desc":"عملاء محتملون بنية شرائية عالية يصلون إلى خط إنتاجك عبر مسارات مستهدفة وصفحات هبوط وحملات محسّنة للتحويل.",
    "s2.title":"الإعلانات المدفوعة","s2.desc":"Meta Ads وGoogle Ads وTikTok Ads وLinkedIn — نُدير ميزانيتك كأنها ميزانيتنا ونهوس بتحقيق أعلى عائد على الإنفاق الإعلاني.",
    "s3.title":"إنشاء المحتوى","s3.desc":"ريلز وكاروسيل وUGC وإنتاج فيديو — محتوى يوقف التمرير ويبني ولاء العلامة التجارية على نطاق واسع.",
    "s4.title":"التسويق بالذكاء الاصطناعي","s4.desc":"نصوص إعلانية مدعومة بالذكاء الاصطناعي وسير عمل آلي وروبوتات محادثة واستهداف تنبؤي — مستقبل التسويق، اليوم.",
    "s5.title":"بناء العلامة التجارية","s5.desc":"أنظمة الهوية والتموضع واللغة البصرية — نبني علامات تجارية يتذكرها الناس ويخشاها المنافسون.",
    "s6.title":"التجارة الإلكترونية والأتمتة","s6.desc":"متاجر Shopify وتدفقات البريد الإلكتروني وأتمتة CRM والاستهداف المعاد — أنظمة نمو إلكتروني متكاملة تعمل 24/7.",
    "s7.title":"التدقيق والاستشارات التسويقية","s7.desc":"تدقيق شامل للعلامة التجارية — القنوات والمنافسون والمسار والميزانية — مُقدَّم كخطة عمل ملموسة.",
    "s8.title":"إدارة وسائل التواصل الاجتماعي","s8.desc":"إدارة كاملة لوسائل التواصل الاجتماعي — استراتيجية وتقويم محتوى وتصميم وكتابة إبداعية وتفاعل.",
    "s9.title":"تطوير المواقع والتطبيقات","s9.desc":"مواقع وصفحات هبوط وتطبيقات تحوّل الزوار. تصميم احترافي وسرعة حقيقية وتحسين SEO.",
    "about.tag":"من نحن","about.title":"مهووسون بالنمو.","about.p1":"فونا هي وكالة تسويق للنمو مقرها دبي، مبنية للعلامات التجارية الجادة في التوسع. نجمع البيانات والإبداع والأتمتة لبناء أنظمة تسويقية تعمل وأنت نائم.","about.p2":"لا نؤمن بمقاييس الغرور. نؤمن بالإيرادات والعملاء المحتملين وعائد الاستثمار القابل للقياس — مُقدَّم بسرعة وبشفافية تامة.","about.li1":"استراتيجية تسويق النمو","about.li2":"إدارة الإعلانات المدفوعة","about.li3":"إنتاج المحتوى والإبداع","about.li4":"الأتمتة بالذكاء الاصطناعي","about.li5":"تحليلات المسار الكامل","about.cta":"اعمل معنا",
    "results.tag":"سجل الإنجازات","results.title":"نتائج حقيقية.","results.stat1.num":"10X","results.stat1.lbl":"متوسط عائد الإنفاق الإعلاني","results.stat1.sub":"متوسط العائد على الإنفاق الإعلاني عبر جميع حملات الإعلانات المدفوعة في 2024.","results.stat2.num":"+50","results.stat2.lbl":"علامة تجارية مُطوَّرة","results.stat2.sub":"من الشركات الناشئة في دبي إلى المؤسسات الإقليمية في أكثر من 8 صناعات.","results.stat3.num":"+2M","results.stat3.lbl":"عميل محتمل تم توليده","results.stat3.sub":"عملاء محتملون مؤهلون تم تسليمهم لعملائنا عبر حملات الأداء.","results.stat4.num":"98%","results.stat4.lbl":"معدل استبقاء العملاء","results.stat4.sub":"لأن النتائج تتكلم أعلى من الوعود. عملاؤنا يبقون.",
    "process.tag":"كيف نعمل","process.title":"آلية عملنا","process.s1.title":"الاستكشاف","process.s1.desc":"تدقيق معمّق لعلامتك التجارية وسوقك ومنافسيك وأدائك الحالي.","process.s2.title":"الاستراتيجية","process.s2.desc":"خطة نمو مخصصة مع مزيج القنوات وتوزيع الميزانية وأهداف المؤشرات.","process.s3.title":"الإنشاء","process.s3.desc":"إبداعات عالية التحويل ونصوص وصفحات هبوط وأصول الحملة.","process.s4.title":"الإطلاق","process.s4.desc":"إطلاق الحملات عبر جميع القنوات مع المراقبة الفورية والتحسين المستمر.","process.s5.title":"التوسع","process.s5.desc":"مضاعفة ما ينجح وأتمتة الآلة وتحقيق نمو مركّب.",
    "testimonials.tag":"آراء العملاء","testimonials.title":"ماذا يقولون","t1.text":"حوّلت فونا حضورنا الرقمي تماماً. خلال 3 أشهر، تضاعف حجم العملاء المحتملين ثلاث مرات وانخفضت تكلفة العميل بنسبة 60%. إنهم لا يديرون إعلانات فحسب — يبنون أنظمة.","t1.name":"أحمد ك.","t1.role":"الرئيس التنفيذي · مطوّر عقاري، دبي","t2.text":"أفضل قرار تسويقي اتخذناه. ارتفعت إيرادات التجارة الإلكترونية لدينا من 80 ألف درهم إلى 400 ألف درهم/شهر في 6 أشهر. الفريق مهووس بالنتائج وهذا يظهر جلياً.","t2.name":"سارة ل.","t2.role":"مؤسسة · علامة أزياء، الإمارات","t3.text":"فريق المحتوى في فونا استثنائي حقاً. انتقل حساب Instagram الخاص بنا من 2K إلى 18K متابع في 4 أشهر، والأهم أنه يتحوّل فعلاً إلى حجوزات.","t3.name":"ماركو ر.","t3.role":"مدير · مجموعة مطاعم، دبي",
    "cta.tag":"مستعد للتوسع؟","cta.title":"لنبني شيئاً عظيماً معاً.","cta.desc":"أجب على 5 أسئلة سريعة. سنتواصل معك خلال 24 ساعة.",
    "form.step1.title":"ما اسمك واسم شركتك؟","form.step2.title":"كيف يمكننا التواصل معك؟","form.step3.title":"ما الخدمة التي تحتاجها؟","form.step4.title":"ما ميزانيتك الشهرية؟","form.step5.title":"تقريباً انتهينا. أكّد بياناتك.","form.btn.next":"متابعة ←","form.btn.back":"→ رجوع","form.btn.send":"إرسال الرسالة ←","form.success":"سنتواصل معك خلال 24 ساعة. إلى اللقاء!","form.reply":"نردّ خلال 24 ساعة",
    "industries.tag":"القطاعات التي نخدمها",
    "pulse.tag":"تقرير شهري مجاني","pulse.title":"نبض تسويق دبي","pulse.desc":"التقرير الشهري للشركات والمسوّقين في الإمارات. بيانات حقيقية واتجاهات حقيقية، بدون حشو.","pulse.li1":"اتجاهات السوق الإماراتي وتحديثات المنصات","pulse.li2":"ما الذي ينجح في دبي الآن","pulse.li3":"معايير الصناعة وتكاليف الإعلانات","pulse.li4":"نصيحة قابلة للتطبيق في كل عدد","pulse.cta":"احصل على التقرير","pulse.sub":"مجاني. كل شهر. بدون بريد عشوائي أبداً.",
    "footer.desc":"وكالة تسويق النمو · دبي، الإمارات العربية المتحدة","footer.services":"الخدمات","footer.company":"الشركة","footer.industries":"القطاعات","footer.copy":"© 2026 Funa Digital Marketing. جميع الحقوق محفوظة. دبي، الإمارات.","footer.privacy":"سياسة الخصوصية","footer.terms":"الشروط والأحكام"
  }
};
